Name:		ros-groovy-yei-tss-usb
Version:	0.0.2
Release:	0%{?dist}
Summary:	ROS yei_tss_usb package

Group:		Development/Tools
License:	BSD
Source0:	%{name}-%{version}.tar.gz

BuildRequires:	ros-groovy-sensor-msgs,ros-groovy-diagnostic-updater,ros-groovy-catkin,ros-groovy-roscpp,ros-groovy-std-srvs
Requires:	ros-groovy-diagnostic-updater,ros-groovy-sensor-msgs,ros-groovy-roscpp,ros-groovy-std-srvs

%description
YEI Three-space USB Driver


%prep
%setup -q


%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/groovy/setup.sh" ]; then . "/opt/ros/groovy/setup.sh"; fi
mkdir build && cd build
cmake .. \
	-DCMAKE_VERBOSE_MAKEFILE=ON \
	-DCATKIN_BUILD_BINARY_PACKAGE="1" \
	-DCMAKE_INSTALL_PREFIX="/opt/ros/groovy" \
	-DCMAKE_PREFIX_PATH="/opt/ros/groovy" \
	-DSETUPTOOLS_DEB_LAYOUT=OFF
make %{?_smp_mflags}


%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/groovy/setup.sh" ]; then . "/opt/ros/groovy/setup.sh"; fi
cd build
make install DESTDIR=%{buildroot}


%files
%doc
/opt/ros/groovy


%changelog
* Sat Feb 23 2013 Scott K Logan <logans@cottsay.net> - 0.0.2-0
- autogenerated

